/*
 * IBudgetActionPublisher.java
 *
 * Created on 7 December 2005, 18:31
 *
 * To change this template, choose Tools | Options and locate the template under
 * the Source Creation and Management node. Right-click the template and choose
 * Open. You can then make changes to the template in the Source Editor.
 */

package com.rochester.budget.gui;

import java.awt.event.ActionListener;

/**
 *
 * @author Cam
 */
public interface IBudgetActionPublisher
{
    /** Can't use enums in ActionEvent.getID, otherwise I would! **/
    
    // Generated by ReconciliationPanel
    static final int NEXT_TRANSACTION = 1;
    static final int PREV_TRANSACTION = 2;
    
    // Generated by TransactionPanel
    static final int TRANS_SELECTION_CHANGED = 3;
    
    void addActionListener( ActionListener l );
    
    void removeActionListener( ActionListener l );
}
